export type TenantStatus = 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'PENDING';

export interface TenantSettings {
  maxApplications: number;
  maxDailyNotifications: number;
  allowedChannels: ('EMAIL' | 'SMS' | 'PUSH' | 'WEBHOOK')[];
  customDomain?: string;
  supportEmail?: string;
}

export interface Tenant {
  id: string;
  name: string;
  slug: string;         // returned by the backend, used for display only
  status: TenantStatus;
  apiKey: string;
  settings: TenantSettings;
  applicationsCount: number;
  usersCount: number;
  createdAt: string;
  updatedAt: string;
}

// slug removed — generated by the backend from the name
export interface CreateTenantPayload {
  name: string;
  status?: TenantStatus;
  settings: TenantSettings;
}

export interface UpdateTenantPayload extends Partial<CreateTenantPayload> {
  id: string;
}
