// Backend status values — must match what the API returns (case-normalised below)
// The spec has: Active | Suspended | Disabled (no Inactive / Pending)
export type TenantStatus = 'ACTIVE' | 'SUSPENDED' | 'DISABLED';
export interface TenantSettings {
  maxApplications: number;
  maxDailyNotifications: number;
  allowedChannels: ('EMAIL' | 'SMS' | 'PUSH' | 'WEBHOOK')[];
  customDomain?: string;
  supportEmail?: string;
}

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  status: TenantStatus;
apiKey: string;          // apiKeyMasked from the list DTO  settings: TenantSettings;
  applicationsCount: number;
  usersCount: number;
  createdAt: string;
  updatedAt: string;
}

// slug is generated by the backend — not part of the create payload
export interface CreateTenantPayload {
  name: string;  status?: TenantStatus;
  settings: TenantSettings;
}

export interface UpdateTenantPayload extends Partial<CreateTenantPayload> {
  id: string;
}

